Repository Automattic/vip-security-boost, pull requests merged in 2025-08, with the labels that each got.

#75 Fix network-wide user queries with capability filtering
  modules/highlight-mfa-users/class-highlight-mfa-users.php
  modules/inactive-users/class-inactive-users.php
  tests/phpunit/test-inactive-users.php
  tests/phpunit/test-users-query-utils.php
  utils/class-users-query-utils.php
Labels: [Status] Needs Review

#81 [PLTFRM-1497] Fix cache keys for 2FA disabled SDS data
  modules/highlight-mfa-users/class-highlight-mfa-users.php
Labels: [Status] Needs Review

#84 Move SDS MFA count from `highlight-mfa-users` to `forced-mfa-users`
  modules/forced-mfa-users/class-forced-mfa-users.php
  modules/highlight-mfa-users/class-highlight-mfa-users.php
  tests/phpunit/test-forced-mfa-users.php
  tests/phpunit/test-highlight-mfa-users.php
Labels: [Status] Has Feedback, [Status] Ready to Merge

#85 [PLTFRM-1510] Set `highlight-mfa-users` to Admin and Editor roles by default
  modules/highlight-mfa-users/class-highlight-mfa-users.php
  tests/phpunit/test-highlight-mfa-users.php
Labels: [Status] Ready to Merge

#89 Add checking if `Two_Factor_Core` exists before registering hooks
  modules/forced-mfa-users/class-forced-mfa-users.php
Labels: [Status] Needs Review

#92 fix: prevent null reference errors by returning early if user is not found
  modules/inactive-users/class-inactive-users.php
Labels: [Status] Needs Review
